Faleev Alex
rmasgutov/school57kotlin pull request #52
Opened 2024-09-21 15:12 UTC by good-atom

2024-09-25 17:07 UTC, physcorgi requested changes

2024-09-25 17:07 UTC, physcorgi commented on lesson2/src/main/kotlin/ru/tbank/education/school/lesson2/DemoList.kt
при обращении к каждой новой функции создаётся новый лист, поэтому лучше создать только один и принимать все другие функции только на него (а не на новый лист каждый раз). Нужно добавить  
private val list: List<Int> = createList() и заменить все createList() на list.  Также лучше заменить max на maxOrNull()(у меня тоже в коде max, но я прочитал, что этот метод устарел)

2024-09-25 17:07 UTC, physcorgi commented on lesson2/src/main/kotlin/ru/tbank/education/school/lesson2/DemoMap.kt
Здесь также нужно заменить createMap() на map, тем более в коде он уже есть, и опять поменять max() на maxOrNull()

2024-09-25 18:13 UTC, physcorgi approved these changes
кайф

2024-09-27 14:35 UTC, Monax111 commented
Молодцы, оценка 5

2024-09-27 14:35 UTC, closed without merging